import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
    <Head>
      <title>Home do site de spa</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <h1>Bem vindo a página inicial do nosso site!</h1>
      <Link href="/dashboard/categoria">
      <button>Dashboard</button>
      </Link>
    </div>
    </>
  )
}
